### ISSUE TITLE
Blame not found for comment

### ISSUE THREAD

**Issue by pouryafard75** [jodavimehran/code-tracker#197]
[dbc805e237b98834a7b7afb6da7be44da428c399](https://github.com/apache/tomcat/blob/dbc805e237b98834a7b7afb6da7be44da428c399/java/org/apache/coyote/http2/ConnectionSettings.java#L31)

<img width="766" alt="image" src="https://github.com/user-attachments/assets/f7523dc8-8281-4e82-bacb-8e52b96baa84">

**Comment by tsantalis** [comment]
@pouryafard75 
The tool reports the commit https://github.com/apache/tomcat/commit/a883a6b3dd2c096220e0e0ab2c0614773bb60787

```java
CommentTracker commentTracker = CodeTracker.commentTracker()
      .repository(repository)
      .filePath("java/org/apache/coyote/http2/ConnectionSettings.java")
      .startCommitId("dbc805e237b98834a7b7afb6da7be44da428c399")
      .codeElementType(CodeElementType.LINE_COMMENT)
      .methodName("UNLIMITED")
      .methodDeclarationLineNumber(32)
      .commentStartLineNumber(31)
      .commentEndLineNumber(31)
      .build();
 HistoryInfo<Comment> h = commentTracker.blame();
```

**Comment by tsantalis** [comment]
@pouryafard75 

But FileTracker gives no blame

**Comment by tsantalis** [comment]
@pouryafard75 
The issue has been fixed.
The problem was that when there is a comment in the same line with the attribute, the `CodeElementLocator` was returning the comment instead of the attribute.

Now priority is given to the attribute in such scenario.
This means the most dominant code element in the line should be the attribute instead of the comment.
