### ISSUE TITLE
Invalid Change History - org.springframework.beans/src/main/java/org.springframework.beans.factory.support.ConstructorResolver#instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[])$if(392-394)

### ISSUE THREAD

**Issue by flozender** [jodavimehran/code-tracker#72]
In commit [`9857ba077b16312e78ca6dcf2a219326955daae5`](https://github.com/spring-projects/spring-framework/commit/9857ba077b16312e78ca6dcf2a219326955daae5#diff-ebd0ea1d06e527f37e953e4f287020385274073bf8f50074e741e0601f3776f1R392?diff=split#diff-ebd0ea1d06e527f37e953e4f287020385274073bf8f50074e741e0601f3776f1R392) and file `org.springframework.beans/src/main/java/org/springframework/beans/factory/support/ConstructorResolver.java`, element `org.springframework.beans/src/main/java/org.springframework.beans.factory.support.ConstructorResolver#instantiateUsingFactoryMethod(String, RootBeanDefinition, Object[])$if(392-394)` was identified as being `introduced`, which may not be accurate. 

Oracle filename: `spring-framework-ConstructorResolver-instantiateUsingFactoryMethod-IF_STATEMENT-6.json`

**Comment by flozender** [comment]
Should match with [`L378`](https://github.com/spring-projects/spring-framework/commit/9857ba077b16312e78ca6dcf2a219326955daae5#diff-ebd0ea1d06e527f37e953e4f287020385274073bf8f50074e741e0601f3776f1L378)

**Comment by tsantalis** [comment]
@flozender 
Based on the diff
statement L379 has been moved to R393 and place under a new `if ` R392-394.
I think it is correct to say that `if(392-394)` is introduced.

The only problem is that we do not match **L378-380** with **R387-389**
and the reason is that no statement is mapped within the bodies of these two `if` statements.

![Screenshot from 2022-12-06 09-24-37](https://user-images.githubusercontent.com/1483516/205937735-1e038695-d252-4412-aac4-a7326cc7b921.png)

**Comment by flozender** [comment]
Thank you, I understand, that makes more sense.
